services:
  django:
    build: .
    container_name: jobboard_django
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - /.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  celery:
    build: .
    container_name: jobboard_celery
    command: celery -A core worker --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - /.env
    depends_on:
      - django
      - redis
      - postgres

  celery_beat:
    build: .
    container_name: jobboard_celery_beat
    command: celery -A core beat --loglevel=INFO
    volumes:
      - .:/app
    env_file:
      - /.env
    depends_on:
      - django
      - redis
      - postgres


  flower:
    build: .
    container_name: jobboard_flower
    command: celery -A core flower --port=5555 --loglevel=INFO
    ports:
      - "5555:5555"
    env_file:
      - /.env
    depends_on:
      - redis
      - django


  postgres:
    image: postgres:15
    container_name: jobboard_postgres
    env_file:
      - /.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: jobboard_redis
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    restart: always
    container_name: jobboard_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume:
